name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: build
        run: npm run build
  test:
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: Jest tests
        run: npm run test
      # - name: Cypress e2e tests
      #   uses: cypress-io/github-action@v2
      #   with:
      #     command: npm run test:e2e
      #     start: npm run start-prod
      #     wait-on: http://localhost:5000
  version:
    needs: test
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: version
      if : ${{ !contains(github.event.head_commit.message, '#skip') }}
      uses: anothrNick/github-tag-action@1.33.0
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
  deploy:
    needs: version
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
       heroku_api_key: ${{secrets.HEROKU_API_KEY}}
       heroku_app_name: "fullstack2021-osa11"
       heroku_email: ${{secrets.HEROKU_EMAIL}}}
       healthcheck: "https://fullstack2021-osa11.herokuapp.com/health"
       checkstring: "OK"
       rollbackonhealthcheckfailed: true
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: deploy to Heroku
      if: |
        ${{ github.event_name == 'push' }}
        §§
        ${{ !contains(github.event.head_commit.message, '#skip') }}
      run: echo "Deploy"
  notify:
    runs-on: ubuntu-18.04
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author
          #fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always()
