name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      #- name: npm install
      #  run: npm install
      #- name: lint
      #  run: npm run eslint
      #- name: build
      #  run: npm run build
      #- name: Jest tests
      #  run: npm run test
      # - name: Cypress e2e tests
      #   uses: cypress-io/github-action@v2
      #   with:
      #     command: npm run test:e2e
      #     start: npm run start-prod
      #     wait-on: http://localhost:5000
      - name: testing1
        env: 
          TEST1: ${{ toJson(github.event.commits.*.message) }}
        run: echo $TEST1
      - name: testing2
        env: 
          TEST2: ${{ !contains(toJson(github.event.commits.*.message), '[#skip]') }}
        run: echo $TEST2
      - name: testing3
        if : ${{ !contains(github.event.head_commit.message, '#skip') }}
        run: echo "Testing"
      - name: version
        ##if : ${{ github.event_name == 'push' }} && {{ !contains(github.event.commits.*.message, '#skip') }}
        if : ${{ !contains(github.event.commits.*.message, '#skip') }}
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
      - name: deploy to Heroku
        if: ${{ github.event_name == 'push' }} && {{ !contains(github.event.commits.*.message, '#skip') }}
        run: echo "Deploy"
     #   uses: akhileshns/heroku-deploy@v3.12.12
     #   with:
     #     heroku_api_key: ${{secrets.HEROKU_API_KEY}}
     #     heroku_app_name: "fullstack2021-osa11"
     #     heroku_email: ${{secrets.HEROKU_EMAIL}}}
     #     healthcheck: "https://fullstack2021-osa11.herokuapp.com/health"
     #     checkstring: "OK"
     #     rollbackonhealthcheckfailed: true
